# Generated by Django 5.1.2 on 2025-08-11 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
            options={
                'verbose_name': 'Ingreso diario',
                'verbose_name_plural': 'Ingresos registrados',
            },
        ),
    ]
