# Generated by Django 5.1.2 on 2025-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField()),
                ('dias_restantes', models.IntegerField(default=0)),
                ('id_membresia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios registrados',
                'permissions': [('view', 'Puede ver socios'), ('add', 'Agregar socio'), ('change', 'Editar socio'), ('delete', 'Eliminar socio')],
            },
        ),
    ]
