# Generated by Django 5.1.2 on 2025-08-11 19:20

import membresias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, validators=[membresias.models.validate_tipo])),
                ('precio', models.FloatField(validators=[membresias.models.validate_precio])),
                ('duracion', models.IntegerField(validators=[membresias.models.validate_duracion])),
            ],
            options={
                'verbose_name_plural': 'Membresias registradas',
            },
        ),
    ]
