# Generated by Django 5.1.2 on 2025-08-11 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('EF', 'Efectivo'), ('DB', 'Débito'), ('TR', 'Transferencia')], max_length=2)),
                ('ruta_recibo', models.FileField(blank=True, null=True, upload_to='')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='caja.caja')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Pagos registrados',
            },
        ),
    ]
